# -*- coding: utf-8 -*-
"""Employee_Details.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zkzhs-KCtVqXMOkGVulzet6YGKTcGyf5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("/content/employee_raw.xlsx")
df.info()
df.head(3)

df['JoiningDate'] = pd.to_datetime(df['JoiningDate'])
df['Year'] = df['JoiningDate'].dt.year
df['Month'] = df['JoiningDate'].dt.month_name()

df.isnull().sum()

df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Role'] = df['Role'].fillna("Unknown")

df['Department'].value_counts()

df['Gender'].value_counts()

df['Department'] = df['Department'].str.strip().str.title()
df['Name'] = df['Name'].str.strip().str.title()
df['Role'] = df['Role'].str.strip().str.title()

df['Role'].value_counts()

df['Department'] = df['Department'].replace('hr', 'HR')
df['Department'] = df['Department'].replace('It', 'IT')
df['Role'] = df['Role'].replace('SysAdmin', 'System Admin')
df['Role'] = df['Role'].fillna("Unknown")

emp_dep = df.groupby('Department')['Salary'].count()
emp_dep

df.info()

avg_salary = df.groupby('Department')['Salary'].mean()
avg_salary

df['Gender'].nunique()

df['Gender'] = df['Gender'].replace('M', 'Male')
df['Gender'] = df['Gender'].replace('F', 'Female')
df['Gender'] = df['Gender'].str.strip().str.title()

att_gender = df.groupby(['Gender', 'Attrition'])['EmployeeID'].count().unstack()
att_gender

high_salary = df.sort_values(by='Salary', ascending=False).head(5)
print("\nTop 5 Highest Paid Employees:")
display(high_salary[['EmployeeID', 'Name', 'Department', 'Role', 'Salary']])

emp_dep.plot(kind='bar', color="blue")
plt.title("Number of Employees by Department")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.show()

avg_salary.plot(kind='bar', color='seagreen')
plt.title("Average Salary by Department")
plt.xlabel("Department")
plt.ylabel("Average Salary")
plt.show()

import matplotlib.ticker as mticker
hiring_trend = df.groupby('Year')['EmployeeID'].count()
hiring_trend.plot(kind='line', color='blue', marker="o")
plt.title("Hiring Trend Over Years")
plt.xlabel("Year")
plt.ylabel("Number of Employees Hired")
plt.gca().yaxis.set_major_formatter(mticker.FormatStrFormatter('%d'))
plt.show()

att_gender.plot(kind='bar', color=['mediumblue', 'seagreen'])
plt.title("Attrition by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Employees")
plt.legend(title="Attrition")
plt.xticks(rotation=0)
plt.show()

att_dept = df.groupby(['Department', 'Attrition'])['EmployeeID'].count().unstack()

att_dept.plot(kind='bar', stacked=False, figsize=(8,5), color=['seagreen', 'mediumblue'])
plt.title("Attrition by Department")
plt.ylabel("Number of Employees")
plt.xlabel("Department")
plt.legend(title="Attrition")
plt.xticks(rotation=45)
plt.show()

df['PerformanceRating'].value_counts().sort_index().plot(kind='bar', color='royalblue')
plt.title("Performance Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Number of Employees")
plt.grid(axis='y')
plt.show()



